name: star
description: A new Flutter project.



publish_to: 'none'











version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"







dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  badges: ^2.0.3
  curved_navigation_bar: ^1.0.3
  get: ^4.6.5

  google_fonts:
dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^1.0.0





flutter:


  uses-material-design: true
  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
